# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24e962b04863787ee8a960d32ae86b684ca1a83cd806d22c34f3e01681fd93c68d29d6fa01fcfac6d644814dbb0ed9f87dbfe1312096cb05a4f7d78cfad2e5ac

test:
  secret_key_base: 97efd46a05461840bd8ad5b92c70664e2301a9fe17d5666487fcf672fc36423c4238f006c9f31b24005bb5ce4dbd325d7699742be624949840499d68f3f2a3df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
